### ISSUE TITLE
Error: package or namespace load filed

### ISSUE THREAD

**Issue by maittha** [mdsumner/ozplot#12]
Hi,
I have installed package 'ozmaps' and 'sf'. When i use library(sf) it automatically closes my R and restarts. and with library(ozmaps) it shows the error below:

`Error: package or namespace load failed for ‘ozmaps’:
 .onLoad failed in loadNamespace() for 'sf', details:
  call: CPL_set_data_dir(prj)
  error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'`

**Comment by mdsumner** [comment]
This isn't the home of ozmaps, this just an old copy. Please report at the home listed in the package for BugReports.
